services:
  cronicle:
    image: soulteary/cronicle:0.9.80
    hostname: cronicle-primary
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache openssh-client && exec docker-entrypoint.sh node bin/docker-entrypoint.js"]
    environment:
      - CRONICLE_base_app_url=http://${APP_DOMAIN}
    volumes:
      - ${APP_DATA_DIR}/data:/opt/cronicle/data
      - ${APP_DATA_DIR}/logs:/opt/cronicle/logs
      - ${APP_DATA_DIR}/plugins:/opt/cronicle/plugins
      - ${APP_DATA_DIR}/ssh:/opt/cronicle-ssh
    x-runtipi:
      is_main: true
      internal_port: '3012'
x-runtipi:
  schema_version: 2
